version: '3'

services:
  
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}   
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - mylocal
      
  app:
    build: .
    container_name: proxy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
    networks:
        - mylocal
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/swagger.yaml
    volumes:
      - ./docs/swagger.yaml:/swagger.yaml
    networks:
      - mylocal

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - swagger
    networks:
      - mylocal 

networks:
  mylocal:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

